add-reviews
AlexeiRomanchenko/java-filmorate pull request #14
Opened 2023-07-06 10:56 UTC by ARGalimov

Функциональность "Отзывы" + поправил схему БД

2023-07-06 22:11 UTC, AlexeiRomanchenko approved these changes
Хороший код, замечаний нет.

2023-07-07 04:01 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public int getUseful() {
Можно улучшить с помощью стрима: 
        return grades.values().stream().mapToInt(positive -> positive ? 1 : -1).sum();
}

2023-07-07 05:16 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new ObjectNotFoundException(LogMessagesReviews.MSG_ERR_NOT_FOUND.getMessage() + id);
Мне кажется тут логичнее кидать BadRequestException(LogMessagesReviews.MSG_ERR_ID.getMessage());

2023-07-07 05:23 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +    public Review findById(Integer id) {
Тут лучше будет возвращать Optional<Review>, так потом в сервисе одной строкой можно вытащить значение или кинуть исключение

2023-07-07 05:28 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +        jdbcTemplate.update("DELETE FROM REVIEW_USEFUL WHERE REVIEW_ID = ?", id);
jdbcTemplate.update возвращает число измененных строк в бд, если прокинуть его дальше в сервис то не нужно будет дополнительно вызывать findById чтобы кинуть исключение, а просто проверить больше ли оно нуля

2023-07-07 05:30 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Review review = reviewStorage.findById(id);
Написал в комменте к хранилищу как можно обойтись без вызова этого метода

2023-07-07 06:31 UTC, elGordoGato requested changes
В целом все круто, может быть не стоило делать мапу с оценками в классе отзыва и в нем ограничиться только интовым полем с суммой оценок, т.к. все хранение и так в бд, а в классе это все хранить не вижу смысла, но это чисто для размышления.
Из критичного только проблему n+1 считаю стоит поправить

2023-07-07 06:31 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviews.forEach(reviewStorage::loadGrades);
Тут N+1 проблема, типа если у тебя 100 отзывов, то нужно будет сделать запрос к бд на получение всех отзывов, а потом еще 100 запросов на получение оценок к ним, итого 101 запрос, а можно:

1. Сделать запрос на получение всех отзывов
2. Сделать запрос на получение всех оценок ко всем отзывам и потом в сервисе уже заполнить оценки к каждому отзыву

Итого 2 запроса вместо 101, там еще вроде можно и одним запросом это все провернуть объединив таблицы, но я так еще не делал :) 
Вот тут описывают суть проблемы: https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping

2023-07-07 06:31 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void delDislike(Integer id, Integer userId) {
Не вижу смысла в этом методе, полностью копирует delLike

2023-07-07 06:31 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviews.forEach(reviewStorage::loadGrades);
тоже N+1

2023-07-07 06:37 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public int getUseful() {
согласен, в одну строку решение лучше. Поправил

2023-07-07 06:39 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new ObjectNotFoundException(LogMessagesReviews.MSG_ERR_NOT_FOUND.getMessage() + id);
Не согласен, в тестах тут ожидается код 404. А BadRequest вернет код 400

2023-07-07 06:52 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +        jdbcTemplate.update("DELETE FROM REVIEW_USEFUL WHERE REVIEW_ID = ?", id);
Переделал

2023-07-07 06:53 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Review review = reviewStorage.findById(id);
переделал

2023-07-07 07:02 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void delDislike(Integer id, Integer userId) {
Точно, убрал этот метод

2023-07-07 07:41 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviews.forEach(reviewStorage::loadGrades);
Переделал

2023-07-07 07:42 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviews.forEach(reviewStorage::loadGrades);
Тоже переделал

2023-07-07 08:58 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +            reviewMap.put(review.getReviewId(), review);
Можно заменить на стрим Map<Integer, Review> reviewMap = reviews.stream().collect(Collectors.toMap(Review::getReviewId, Function.identity()));

2023-07-07 09:07 UTC, elGordoGato approved these changes
Все хорошо, принял

2023-07-07 09:21 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/ReviewDbStorage.java
> +            reviewMap.put(review.getReviewId(), review);
заменил

2023-07-07 09:24 UTC, merged