Функциональность «Рекомендации»
AlexeiRomanchenko/java-filmorate pull request #17
Opened 2023-07-07 10:06 UTC by elGordoGato

Описание задачи
Реализовать простую рекомендательную систему для фильмов. Примерный алгоритм выглядит следующим образом:

- Найти пользователей с максимальным количеством пересечения по лайкам.
- Определить фильмы, которые один пролайкал, а другой нет.
- Рекомендовать фильмы, которым поставил лайк пользователь с похожими вкусами, а тот, для кого составляется рекомендация, ещё не поставил.

Более подробно подобный алгоритм описан в этой [[статье](https://www.baeldung.com/java-collaborative-filtering-recommendations)](https://www.baeldung.com/java-collaborative-filtering-recommendations).

API
GET /users/{id}/recommendations

Возвращает рекомендации по фильмам для просмотра.

2023-07-07 14:41 UTC, ARGalimov requested changes

2023-07-07 14:41 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        jdbcTemplate.update("DROP TABLE IF EXISTS likes_rank;");
Зачем временную таблицу сохранять в БД и чистить при каждом использовании? Давай переделаем на локальную MAP или LIST

2023-07-08 08:03 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        jdbcTemplate.update("DROP TABLE IF EXISTS likes_rank;");
В локальную мапу не получится т.к. не понятно как потом выдачу сортировать по рангу если только не делать отдельно запрос на каждый ключ из этой мапы, т.е. каждой строке в таблице надо соотнести как-то значение по ключу из мапы, мне кажется это невозможно, сделал проще через подтаблицу прям внутри запроса

2023-07-08 08:17 UTC, ARGalimov approved these changes

2023-07-09 09:32 UTC, AlexeiRomanchenko reviewed
В общем не плохой код, немного нужно подправить,
чтобы код смотрелся более лаконично

2023-07-09 09:32 UTC, AlexeiRomanchenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sqlQuery = "WITH likes_rank AS " +
Предлагаю вынести запросы к базе данных в отдельный файл application-film.yml и использовать в коде с помощью аннотации @Value (Spring)

2023-07-09 10:23 UTC, elGordoGato commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sqlQuery = "WITH likes_rank AS " +
Захреначил

2023-07-12 19:02 UTC, AlexeiRomanchenko reviewed
Отлично

2023-07-12 19:03 UTC, AlexeiRomanchenko approved these changes
Отлично

2023-07-13 09:45 UTC, merged