Разработать функциональность "Лента событий"
AlexeiRomanchenko/java-filmorate pull request #20
Opened 2023-07-08 08:47 UTC by ARGalimov

V1

2023-07-08 22:27 UTC, AlexeiRomanchenko reviewed
Хороший код. Немного нужно подкорректировать.

2023-07-08 22:27 UTC, AlexeiRomanchenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    EventService eventService;
Это поле следует инкапсулировать и финализировать

2023-07-09 06:44 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    EventService eventService;
Исправил

2023-07-09 08:09 UTC, AlexeiRomanchenko reviewed
Все хорошо, принял

2023-07-09 09:27 UTC, elGordoGato commented on src/test/java/ru/yandex/practicum/filmorate/FilmServiceTest.java
А почему классы с тестами удалил?

2023-07-09 09:28 UTC, elGordoGato approved these changes
Код хороший, но почему удалены классы с тестами?

2023-07-12 19:05 UTC, AlexeiRomanchenko requested changes
Хороший код

2023-07-12 19:37 UTC, AlexeiRomanchenko approved these changes
принято

2023-07-13 02:57 UTC, merged